version: "3"
services:
  sshfs:
    build: ./sshfs
    ports:
      - "${SSH_PORT}:22"
    volumes:
      - /data/sshfs:/data
      - /data/sshfs/etc/root.ssh:/root/.ssh
    privileged: true
    hostname: sshfs
    restart: always
