version: "3"
services:
  sshfs:
    build: ./sshfs
    ports:
      - "${SSH_PORT}:22"
    volumes:
      - /data/sshfs:/data
      - /data/sshfs/etc/root.ssh:/root/.ssh
    privileged: true
    hostname: sshfs
    restart: always

  admin:
    depends_on:
      - sshfs
    image: phwoolcon/sshfs-admin
    ports:
      - "${HTTP_PORT}:8000"
    volumes:
      - /data/admin:/data
      - /data/admin/log:/data/log
      - /data/sshfs/etc/root.ssh:/data/sshfs/etc/root.ssh
    hostname: sshfs-admin
    restart: always
