version: "3"
services:
  dive:
    image: wagoodman/dive
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: dive
    restart: always
    entrypoint: ["tail", "-f", "/dev/null"]
