version: "3"
services:
  fpm74:
    user: "${UID}:${GID}"
    image: php:7-fpm-alpine
    restart: always
    container_name: php-fpm74
    hostname: php-fpm74
    entrypoint: /entrypoint.sh
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/passwd:/etc/passwd
      - /etc/group:/etc/group
      - "${WWW_ROOT}:${WWW_ROOT}"
      - ../entrypoint.sh:/entrypoint.sh
    ports:
      - "${FPM_PORT}:9000"
    working_dir: "${WWW_ROOT}"
