FROM phwoolcon/phwoolcon

ARG ALPINE_REPO=""
ARG UTILS_BASE="https://raw.githubusercontent.com/phwoolcon/docker-utils/master"
RUN pick-mirror v3.9; \
    apk add --no-cache vim shadow curl htop iftop iotop; \
    wget ${UTILS_BASE}/dusort -O /usr/local/bin/dusort; \
    wget ${UTILS_BASE}/phwoolcon/before-entrypoint -O /before-entrypoint; \
    wget ${UTILS_BASE}/phwoolcon/before-service -O /before-service; \
    chmod +x /usr/local/bin/dusort /before-entrypoint /before-service;
VOLUME /srv/http
